"""Generates isopatch/patches.go from the .pnach, for the ISO patcher.

The .pnach keeps the mod's code below the game (000FF000-000FFFFF). In the patched ISO that code moves
to a new loadable section at 004A3500 (a gap the game never uses), so every address and every j/jal into
the old area is shifted by the same amount. The .pnach's difficulty marker (000FE110) is replaced by a
level word inside the new section.

Run: python tools/build_isopatch.py
"""
import re, sys, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PNACH = os.path.join(ROOT, "patches", "SLUS-21242_D224D348.pnach")
OUT = os.path.join(ROOT, "isopatch", "patches.go")

OLD_LO, OLD_HI = 0x000FF000, 0x00100000
NEW_BASE = 0x004A3500                  # free gap between .data and .rodata (loaded as zeros otherwise)
SEG_SIZE = 0xC00
LEVEL_ADDR = NEW_BASE + SEG_SIZE - 0x10  # 004A40F0
MARKER = 0x000FE110
DELTA = NEW_BASE - OLD_LO

def reloc_addr(a):
    return a + DELTA if OLD_LO <= a < OLD_HI else a

def reloc_word(w):
    op = w >> 26
    if op in (2, 3):  # j / jal
        target = (w & 0x3FFFFFF) << 2
        if OLD_LO <= target < OLD_HI:
            return (op << 26) | ((target + DELTA) >> 2)
    return w

def groups(text):
    out, name = {}, None
    for line in text.splitlines():
        m = re.match(r"\[(.+)\]", line.strip())
        if m:
            name = m.group(1); out[name] = []
            continue
        m = re.match(r"patch=1,EE,([0-9A-Fa-f]{8}),word,([0-9A-Fa-f]{8})", line.strip())
        if m and name:
            out[name].append((int(m.group(1), 16), int(m.group(2), 16)))
    return out

def level_patches(g, level_name, level_num):
    words = {}
    for name in ("Nuzlocke\\Block dead cars in garage", "Nuzlocke\\Block pause-menu Retry and Quit",
                 "Nuzlocke\\Harder AI\\" + level_name):
        for a, w in g[name]:
            if a == MARKER:
                continue
            if a < 0x00100000 and not OLD_LO <= a < OLD_HI:
                sys.exit(f"{name}: {a:08X} is below the game but outside the relocated area")
            na, nw = reloc_addr(a), reloc_word(w)
            if NEW_BASE <= na < NEW_BASE + SEG_SIZE and na >= LEVEL_ADDR:
                sys.exit(f"{name}: {na:08X} doesn't fit in the new section")
            words[na] = nw
    words[LEVEL_ADDR] = level_num
    return sorted(words.items())

def main():
    g = groups(open(PNACH).read())
    lines = ["// Code generated by tools/build_isopatch.py from patches/SLUS-21242_D224D348.pnach. DO NOT EDIT.", "",
             "package main", "",
             f"const newBase = 0x{NEW_BASE:08X}",
             f"const newSize = 0x{SEG_SIZE:X}",
             f"const levelAddr = 0x{LEVEL_ADDR:08X}", "",
             "type word struct{ addr, value uint32 }", "",
             "var levels = []struct {", "\tname  string", "\twords []word", "}{"]
    for num, name in enumerate(("Easy", "Medium", "Hard"), 1):
        lines.append(f'\t{{"{name}", []word{{')
        for a, w in level_patches(g, name, num):
            lines.append(f"\t\t{{0x{a:08X}, 0x{w:08X}}},")
        lines.append("\t}},")
    lines.append("}")
    open(OUT, "w").write("\n".join(lines) + "\n")
    print("wrote", OUT)

if __name__ == "__main__":
    main()
