"""Generates isopatch/patches.go from the .pnach, for the ISO patcher.

The .pnach keeps the mod's code below the game (000FF000-000FFFFF), which isn't part of the game file.
In the patched ISO each block of that code moves into unused space inside the game's own .data
section: the end of a 40 KB block of zeros (00470258-0047A25F) that nothing in the game refers to
and that is still all zeros mid-race. The file's layout (headers, sections) is left alone. Each block
is moved as a whole (the code is position independent), and every j/jal into the old area is
retargeted. The .pnach's difficulty marker (000FE110) is replaced by a level word in the same space.

Run: python tools/build_isopatch.py
"""
import re, sys, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PNACH = os.path.join(ROOT, "patches", "SLUS-21242_D224D348.pnach")
OUT = os.path.join(ROOT, "isopatch", "patches.go")

# (old start, old end, new start): the code blocks of the .pnach and where they go in the game file
BLOCKS = [
    (0x000FF000, 0x000FF100, 0x00479D00),  # dead-car garage block (0x8C bytes)
    (0x000FF100, 0x000FF140, 0x00479DA0),  # finished-event signal (0x24)
    (0x000FF140, 0x000FF200, 0x00479DD0),  # crash junction block (0x88)
    (0x000FFA00, 0x000FFC00, 0x00479E80),  # AI catch-up wrapper (about 0x140)
]
FREE_LO, FREE_HI = 0x00479D00, 0x0047A000  # the space used; checked to be zero by the patcher
LEVEL_ADDR = 0x00479FF0
MARKER = 0x000FE110

def reloc_addr(a):
    for lo, hi, new in BLOCKS:
        if lo <= a < hi:
            return new + (a - lo)
    return a

def reloc_word(w):
    op = w >> 26
    if op in (2, 3):  # j / jal
        target = (w & 0x3FFFFFF) << 2
        new = reloc_addr(target)
        if new != target:
            return (op << 26) | (new >> 2)
    return w

def groups(text):
    out, name = {}, None
    for line in text.splitlines():
        m = re.match(r"\[(.+)\]", line.strip())
        if m:
            name = m.group(1); out[name] = []
            continue
        m = re.match(r"patch=1,EE,([0-9A-Fa-f]{8}),word,([0-9A-Fa-f]{8})", line.strip())
        if m and name:
            out[name].append((int(m.group(1), 16), int(m.group(2), 16)))
    return out

def level_patches(g, level_name, level_num):
    words = {}
    for name in ("Nuzlocke\\Block dead cars in garage", "Nuzlocke\\Block pause-menu Retry and Quit",
                 "Nuzlocke\\Harder AI\\" + level_name):
        for a, w in g[name]:
            if a == MARKER:
                continue
            na, nw = reloc_addr(a), reloc_word(w)
            if na < 0x00100000:
                sys.exit(f"{name}: {a:08X} is below the game and not in a relocated block")
            if FREE_LO <= na < FREE_HI and na >= LEVEL_ADDR:
                sys.exit(f"{name}: {a:08X} overflows the free space")
            words[na] = nw
    # blocks must not run into each other
    used = sorted(a for a in words if FREE_LO <= a < FREE_HI)
    for (lo, hi, new), nxt in zip(BLOCKS, [b[2] for b in BLOCKS[1:]] + [LEVEL_ADDR]):
        top = max([a for a in used if new <= a < nxt] or [new])
        assert top + 4 <= nxt, f"block at {new:08X} overlaps the next one"
    words[LEVEL_ADDR] = level_num
    return sorted(words.items())

def main():
    g = groups(open(PNACH).read())
    lines = ["// Code generated by tools/build_isopatch.py from patches/SLUS-21242_D224D348.pnach. DO NOT EDIT.", "",
             "package main", "",
             f"const freeLo, freeHi = 0x{FREE_LO:08X}, 0x{FREE_HI:08X} // must be zero in the original file",
             f"const levelAddr = 0x{LEVEL_ADDR:08X}", "",
             "type word struct{ addr, value uint32 }", "",
             "var levels = []struct {", "\tname  string", "\twords []word", "}{"]
    for num, name in enumerate(("Easy", "Medium", "Hard"), 1):
        lines.append(f'\t{{"{name}", []word{{')
        for a, w in level_patches(g, name, num):
            lines.append(f"\t\t{{0x{a:08X}, 0x{w:08X}}},")
        lines.append("\t}},")
    lines.append("}")
    open(OUT, "w").write("\n".join(lines) + "\n")
    print("wrote", OUT)

if __name__ == "__main__":
    main()
